name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check out docker/compose
        uses: actions/checkout@v2
        with:
          repository: docker/compose


      - name: install docker
        uses: docker-practice/actions-setup-docker@master

      - name: build
        run: |
          ls -l; ls -l ../

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: docker-compose-Linux-aarch64
      #     path: ./dist